### ISSUE TITLE
Fitgher Bomber relocs

### ISSUE THREAD

**Issue by mras0** [jotd666/GameRelocs#2]
lb_0c2b2 and lb_0c3fe should probably not be relocated as they're the sprite control words. They're modified by lb_101ce and the relocation is the cause of the HUD graphic glitches. I've temporarily fixed it in the slave by doing:
```
	PL_L	$101f6+2,$0000c2b2 ;101f6: 13c00000c2b2
	PL_L	$101fc+2,$0000c3fe ;101fc: 13c00000c3fe
	PL_L	$10206+2,$0000c2b4 ;10206: 13c00000c2b4
	PL_L	$1020c+2,$0000c400 ;1020c: 13c00000c400
```

Also noticed:
```
	MOVE.L	#$0006e940,bltcpt(A6)	;10d90: 2d7c0006e9400048
	MOVE.L	#$0006eae0,bltcpt(A6)	;10ea4: 2d7c0006eae00048
	MOVE.L	#$0006ec80,bltcpt(A6)	;10fb8: 2d7c0006ec800048
```
which are labels, but probably shouldn't be relocated either :)

**Comment by jotd666** [comment]
hi

err yes and no. Actually I prefer the labels to be relocated THEN
unrelocated if fastmem expansion. I have a derogation list for that

# relocs that put addresses back in chip memory (sprites, copper,
bitplanes, sound...)
derog_labels = {
0XC070,0xc074,0xC075,0xC076,0xC077,       # sprite data
0xc2b2,0X0c3fe,
0xc2b3,0X0c3ff,
0xc2b4,0X0c400,
0x35508,0x35509,0x3550A,0x3550b,0x3550c,
0x354D8,0x354D9,0x354DA,0x354DB,0x354DC,
0xb58a,   # bitplane data (source B)
0x306c4,0x30340,  # source A
0x13a08,0x13aa8,
0x35168,  # mounted weapons
}

The reason is: when debugging / trying to find forgotten relocs, I use
memory watchpoints, and I want as few false alarms as possible. If the cpu
writes into C2B2 it will trip the memory watch when running in chip. So I'm
relocating them, but unrelocating them afterwards if running from fastmem.

There are also "unrelocs" for chipmem, those are rare, needed because label
124A is accessed either in .W or in .L, so it needs unrelocation for the .L
part, and conversion to raw value for the .W part. That value and most
values ranging from 0x19D4 to 0x1A82

This is implemented in "print_relocs.py" post-processing script, which
analyzes reloc hunk and creates the .reloc/.unreloc files.

Moreover, you have to correct addresses +1, +2 as the program accesses
0xc2b2+1 (aka xC2B3 ) and +2. Same for 0xC3FE,3FF,400 else sprite position
is wrong. I don't have any HUD issues with the latest version.

Cheers

**Comment by jotd666** [comment]
Forgot to reply to that part:

Also noticed:
>
> 	MOVE.L	#$0006e940,bltcpt(A6)	;10d90: 2d7c0006e9400048
> 	MOVE.L	#$0006eae0,bltcpt(A6)	;10ea4: 2d7c0006eae00048
> 	MOVE.L	#$0006ec80,bltcpt(A6)	;10fb8: 2d7c0006ec800048
>
> which are labels, but probably shouldn't be relocated either :)
>
> Yes, they are labels outside the program code. As you see they're not
computed as labels because outside program range. There are tables with
addresses 0x6xxxx in the code, I didn't touch them either.

Cheers

**Comment by mras0** [comment]
Thanks for the info, I'm still trying to figure out how your scripts work :)

For the "HUD issue", this is what it looks like for me in WinUAE (and on my 060):
![image](https://user-images.githubusercontent.com/9952017/205732808-4a716d87-78e7-4fe0-a3ee-0c99bf0d0f4d.png)

With CHIP_ONLY the sprite part of the HUD isn't even visible. Maybe I'm using an old version of the reloc tables?

**Comment by jotd666** [comment]
yes, probably, because I fixed that recently.

**Comment by mras0** [comment]
Forgot to close this one. Confirmed fixed.
